### ISSUE TITLE
Error in deployment to production

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#1011]
Ramda is at version 0.25.0, same it has been for 6months+

https://circleci.com/gh/cypress-io/cypress-documentation/7343

```
npm run deploy-prebuilt -- --environment production --scrape

> cypress-documentation@0.0.0 deploy-prebuilt /root/cypress-documentation
> node ./cy_scripts/deploy.js "--environment" "production" "--scrape"


Cypress Docs Deploy
==============================

branch name master
🔥  deploy failed
TypeError: Cannot read property '@@transducer/step' of undefined
    at _isTransformer (/root/cypress-documentation/node_modules/ramda/src/internal/_isTransformer.js:2:20)
    at /root/cypress-documentation/node_modules/ramda/src/internal/_dispatchable.js:36:11
    at /root/cypress-documentation/node_modules/ramda/src/internal/_curry2.js:22:18
    at f1 (/root/cypress-documentation/node_modules/ramda/src/internal/_curry1.js:18:17)
    at Promise_then_fulfilled (/root/cypress-documentation/node_modules/ggit/node_modules/q/q.js:766:44)
    at Promise_done_fulfilled (/root/cypress-documentation/node_modules/ggit/node_modules/q/q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (/root/cypress-documentation/node_modules/ggit/node_modules/q/q.js:1229:9)
    at Pending_become_eachMessage_task (/root/cypress-documentation/node_modules/ggit/node_modules/q/q.js:1369:30)
    at RawTask.call (/root/cypress-documentation/node_modules/asap/asap.js:40:19)
    at flush (/root/cypress-documentation/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
TypeError: Cannot read property '@@transducer/step' of undefined
    at _isTransformer (/root/cypress-documentation/node_modules/ramda/src/internal/_isTransformer.js:2:20)
    at /root/cypress-documentation/node_modules/ramda/src/internal/_dispatchable.js:36:11
    at /root/cypress-documentation/node_modules/ramda/src/internal/_curry2.js:22:18
    at f1 (/root/cypress-documentation/node_modules/ramda/src/internal/_curry1.js:18:17)
    at Promise_then_fulfilled (/root/cypress-documentation/node_modules/ggit/node_modules/q/q.js:766:44)
    at Promise_done_fulfilled (/root/cypress-documentation/node_modules/ggit/node_modules/q/q.js:835:31)
    at Fulfilled_dispatch [as dispatch] (/root/cypress-documentation/node_modules/ggit/node_modules/q/q.js:1229:9)
    at Pending_become_eachMessage_task (/root/cypress-documentation/node_modules/ggit/node_modules/q/q.js:1369:30)
    at RawTask.call (/root/cypress-documentation/node_modules/asap/asap.js:40:19)
    at flush (/root/cypress-documentation/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by bahmutov** [comment]
rerunning with CircleCI environment variable `DEBUG=docs,depoy` https://circleci.com/workflow-run/25caf343-561f-4f4a-a15d-746b1a4ff8e9 Same error
```
deploy checking last deploy info using url https://docs.cypress.io/build.json +0ms
branch name master
🔥  deploy failed
```
