### ISSUE TITLE
Unable to run and build

### ISSUE THREAD

**Issue by calendee** [cypress-io/cypress-documentation#233]
I'm attempting to get Cypress documentation running locally on my machine. Unfortunately, the build and run process just results in errors.

I have tried `npm run build` using Node versions 4.1.0, 8.9.1, and 9.1.0 with varying error output.  When running on v9.1.0, the debug log has the following:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/jn/.nvm/versions/node/v9.0.0/bin/node',
1 verbose cli   '/Users/jn/.nvm/versions/node/v9.0.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.5.1
3 info using node@v9.0.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle cypress-documentation@0.0.0~prebuild: cypress-documentation@0.0.0
6 verbose lifecycle cypress-documentation@0.0.0~prebuild: unsafe-perm in lifecycle true
7 verbose lifecycle cypress-documentation@0.0.0~prebuild: PATH: /Users/jn/.nvm/versions/node/v9.0.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/jn/Documents/Apps/cypress-documentation/node_modules/.bin:/Users/jn/.nvm/versions/node/v9.0.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jn/Library/Android/sdk/platform-tools:/Development/android-sdk/tools
8 verbose lifecycle cypress-documentation@0.0.0~prebuild: CWD: /Users/jn/Documents/Apps/cypress-documentation
9 silly lifecycle cypress-documentation@0.0.0~prebuild: Args: [ '-c', 'npm run clean && npm run deps && gulp pre:build' ]
10 silly lifecycle cypress-documentation@0.0.0~prebuild: Returned: code: 0  signal: null
11 info lifecycle cypress-documentation@0.0.0~build: cypress-documentation@0.0.0
12 verbose lifecycle cypress-documentation@0.0.0~build: unsafe-perm in lifecycle true
13 verbose lifecycle cypress-documentation@0.0.0~build: PATH: /Users/jn/.nvm/versions/node/v9.0.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/jn/Documents/Apps/cypress-documentation/node_modules/.bin:/Users/jn/.nvm/versions/node/v9.0.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/jn/Library/Android/sdk/platform-tools:/Development/android-sdk/tools
14 verbose lifecycle cypress-documentation@0.0.0~build: CWD: /Users/jn/Documents/Apps/cypress-documentation
15 silly lifecycle cypress-documentation@0.0.0~build: Args: [ '-c', 'node --stack-size=8192 ./index.js generate' ]
16 silly lifecycle cypress-documentation@0.0.0~build: Returned: code: 255  signal: null
17 info lifecycle cypress-documentation@0.0.0~build: Failed to exec build script
18 verbose stack Error: cypress-documentation@0.0.0 build: `node --stack-size=8192 ./index.js generate`
18 verbose stack Exit status 255
18 verbose stack     at EventEmitter.<anonymous> (/Users/jn/.nvm/versions/node/v9.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
18 verbose stack     at emitTwo (events.js:135:13)
18 verbose stack     at EventEmitter.emit (events.js:224:7)
18 verbose stack     at ChildProcess.<anonymous> (/Users/jn/.nvm/versions/node/v9.0.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
18 verbose stack     at emitTwo (events.js:135:13)
18 verbose stack     at ChildProcess.emit (events.js:224:7)
18 verbose stack     at maybeClose (internal/child_process.js:943:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
19 verbose pkgid cypress-documentation@0.0.0
20 verbose cwd /Users/jn/Documents/Apps/cypress-documentation
21 verbose Darwin 17.2.0
22 verbose argv "/Users/jn/.nvm/versions/node/v9.0.0/bin/node" "/Users/jn/.nvm/versions/node/v9.0.0/bin/npm" "run" "build"
23 verbose node v9.0.0
24 verbose npm  v5.5.1
25 error code ELIFECYCLE
26 error errno 255
27 error cypress-documentation@0.0.0 build: `node --stack-size=8192 ./index.js generate`
27 error Exit status 255
28 error Failed at the cypress-documentation@0.0.0 build script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 255, true ]
```

**Comment by brian-mann** [comment]
The `.node-version` file specifies `8.4.0` as the intended version.

Switch to that, `rm -rf node_modules` and `npm i` again.

Then run `npm run build`. If that fails look at the scripts and try running each one independently to find the one that is failing.

**Comment by calendee** [comment]
That did the trick.  Thanks!

**Comment by bahmutov** [comment]
Interesting that this worked on windows just for this version of Node

**Comment by cypress-zh** [comment]
> Interesting that this worked on windows just for this version of Node
> […](#)
> Sent from my iPhone
> On Nov 11, 2017, at 21:48, Justin Noel ***@***.***> wrote: That did the trick. Thanks! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

@bahmutov Did you have another version of node which encountered the same problem?
