### ISSUE TITLE
Deployment failing in staging/master

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#2631]
Log from https://circleci.com/gh/cypress-io/cypress-documentation/22064

```
#!/bin/bash -eo pipefail
npm run deploy-prebuilt -- --environment production --scrape

> cypress-documentation@0.0.0 ******-prebuilt /root/cypress-documentation
> node ./cy_scripts/******.js "--environment" "production" "--scrape"

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/root/cypress-documentation/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/root/cypress-documentation/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/root/cypress-documentation/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/root/cypress-documentation/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/root/cypress-documentation/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/root/cypress-documentation/node_modules/vinyl-fs/lib/src/getContents/index.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/root/cypress-documentation/node_modules/vinyl-fs/lib/src/index.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/root/cypress-documentation/node_modules/vinyl-fs/index.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/root/cypress-documentation/node_modules/@cypress/******-bits/node_modules/gulp/index.js:7:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cypress-documentation@0.0.0 ******-prebuilt: `node ./cy_scripts/******.js "--environment" "production" "--scrape"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cypress-documentation@0.0.0 ******-prebuilt script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-18T19_32_36_187Z-debug.log

Exited with code exit status 1
```

The npm debug logs weren't saved for the deplyment jobs (updated this to store in future https://github.com/cypress-io/cypress-documentation/commit/77796dfda6d925f70e673597f1f2e9394fb5da96)

**Comment by jennifer-shehane** [comment]
This was caused by my bumping the node-version from 8.6.0 to 12.8.1  https://github.com/cypress-io/cypress-documentation/pull/2627 as you can see this failure began in this PR https://github.com/cypress-io/cypress-documentation/pull/2627
