### ISSUE TITLE
i18n_spec failing during `deploy-docs-staging` job in CI

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#2634]
Failures: https://dashboard.cypress.io/projects/ma3dkn/runs/11410/failures

Seems related to 'docs-staging' trying to compare itself to 'docs' url.

```
CypressError: Timed out retrying: expected 'https://docs-staging.cypress.io/guides/overview/why-cypress.html' to equal 'https://docs.cypress.io/guides/overview/why-cypress.html'
at cypressErr (https://docs-staging.cypress.io/__cypress/runner/cypress_runner.js:138036:9)
at throwErr (https://docs-staging.cypress.io/__cypress/runner/cypress_runner.js:137969:11)
at Object.throwErrByPath (https://docs-staging.cypress.io/__cypress/runner/cypress_runner.js:138017:3)
at retry (https://docs-staging.cypress.io/__cypress/runner/cypress_runner.js:132299:19)
at onFailFn (https://docs-staging.cypress.io/__cypress/runner/cypress_runner.js:120514:16)
at tryCatcher (https://docs-staging.cypress.io/__cypress/runner/cypress_runner.js:164895:23)
at Promise._settlePromiseFromHandler (https://docs-staging.cypress.io/__cypress/runner/cypress_runner.js:162831:31)
at Promise._settlePromise (https://docs-staging.cypress.io/__cypress/runner/cypress_runner.js:162888:18)
at Promise._settlePromise0 (https://docs-staging.cypress.io/__cypress/runner/cypress_runner.js:162933:10)
at Promise._settlePromises (https://docs-staging.cypress.io/__cypress/runner/cypress_runner.js:163008:18)
at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (https://docs-staging.cypress.io/__cypress/runner/cypress_runner.js:159620:16)
at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (https://docs-staging.cypress.io/__cypress/runner/cypress_runner.js:159630:10)
at Async.drainQueues (https://docs-staging.cypress.io/__cypress/runner/cypress_runner.js:159504:14)
```

**Comment by jennifer-shehane** [comment]
This was introduced in https://github.com/cypress-io/cypress-documentation/pull/2593 - tests should never compare full urls, as this would not work for dev localhost / docs-staging and docs urls.
