### ISSUE TITLE
Algolia documentation scraper not triggered

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#2670]
See https://circleci.com/gh/cypress-io/cypress-documentation/22353

```
  ****** scraping documentation +2m

(node:1072) UnhandledPromiseRejectionWarning: StatusCodeError: 404 - {"message":"Project not found"}
    at new StatusCodeError (/root/cypress-documentation/node_modules/request-promise/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/root/cypress-documentation/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/root/cypress-documentation/node_modules/request-promise/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/root/cypress-documentation/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/root/cypress-documentation/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/root/cypress-documentation/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
(node:1072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1072) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Need to:
1. catch the error and fail the build
2. ~~fix the API call to trigger the scraper~~ Will do the fix separately, just want to see a failing build properly

**Comment by bahmutov** [comment]
uggh, we forgot to return a promise

```
function deployEnvironmentBranch (env, branch) {
  ...
  debug('uploading to S3 dist folder %s', distDir)
  uploadToS3(distDir, env) // forgot "return" here
  .then(() => scrapeDocs(env, branch))
  ...
}
```

**Comment by bahmutov** [comment]
Excellent, the scraping job shows as failing

**Comment by bahmutov** [comment]
Fixed the call to Circle to scrape by updating Circle credentials
