### ISSUE TITLE
deploy to staging is broken

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/cypress-documentation#3172]
https://app.circleci.com/pipelines/github/cypress-io/cypress-documentation/5616/workflows/779ea430-bd86-4f3c-b8b5-ae1f7c317b1c/jobs/26479

```
$ npm run deploy-prebuilt -- --environment staging --force

> cypress-documentation@0.0.0 deploy-prebuilt /Users/gleb/git/cypress-documentation
> node ./cy_scripts/deploy.js "--environment" "staging" "--force"

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/gleb/git/cypress-documentation/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/gleb/git/cypress-documentation/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/gleb/git/cypress-documentation/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/gleb/git/cypress-documentation/node_modules/vinyl-fs/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/gleb/git/cypress-documentation/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:3:10)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/gleb/git/cypress-documentation/node_modules/vinyl-fs/lib/src/getContents/index.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/gleb/git/cypress-documentation/node_modules/vinyl-fs/lib/src/index.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/gleb/git/cypress-documentation/node_modules/vinyl-fs/index.js:4:8)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
```

Seems to be broken once we upgraded from Node 8 to Node 12

Can recreate it locally in Node 12 on Mac

```
NODE_ENV=staging npm run build
npm run deploy-prebuilt -- --environment staging --force
```

The dependency

```
$ npm ls natives
cypress-documentation@0.0.0 /Users/gleb/git/cypress-documentation
└─┬ @cypress/deploy-bits@1.7.1
  └─┬ gulp@3.9.1
    └─┬ vinyl-fs@0.3.14
      └─┬ graceful-fs@3.0.12
        └── natives@1.1.6 
```

Seems we need to upgrade https://github.com/cypress-io/deploy-bits to be compatible with Node 12

**Comment by bahmutov** [comment]
Can recreate in Node 12
```
$ node -e 'require("@cypress/deploy-bits")'
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/gleb/git/cypress-documentation/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/gleb/git/cypress-documentation/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/gleb/git/cypress-documentation/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
```

**Comment by bahmutov** [comment]
opened https://github.com/cypress-io/deploy-bits/issues/3

**Comment by bahmutov** [comment]
https://github.com/cypress-io/deploy-bits/issues/3

**Comment by bahmutov** [comment]
deployed
