### ISSUE TITLE
Documentation Issue: Required Node Version Outdated in NPM Readme

### ISSUE THREAD

**Issue by dzervoudakes** [cypress-io/cypress-documentation#4037]
## I'm submitting a...

```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

## Type of bug / changes

I may be missing some additional context here, though I suspect the NPM README is out of date, specifically regarding the Node version requirement as seen below:

<img width="451" alt="Screen Shot 2021-07-20 at 4 49 58 PM" src="https://user-images.githubusercontent.com/6432641/126405185-e8fe44b5-d085-432b-8de2-65249e9e0b5c.png">

The current `package.json` specifies the Node runtime requires `>= 14.6.0` corresponding to the release of Cypress `v8.0.0`: https://github.com/cypress-io/cypress/blob/develop/package.json#L199

We noticed the issue when attempting to run Cypress in our GitHub Actions workflow using the `cypress/browsers:node12.19.0-chrome86-ff82` image, which would seem to be incompatible.

Ultimately this isn't a blocker as Cypress `v7.7.0` works just fine for the image we're using, though I wanted to bring this to your attention in case the documentation in `cypress/cli/NPM_README.md` is indeed out of date.

**Comment by dzervoudakes** [comment]
Additional context in case it's helpful, here is the error logging we saw in our workflow run using the `cypress-io/github-action@v2` action:

```
A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at Object.userInfo (os.js:270:11)
    at new File (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/lib/util/file.js:26:62)
    at Object.<anonymous> (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/lib/cache.js:8:18)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/lib/project_static.js:10:41)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/lib/modes/run.js:14:23)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.run (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/lib/modes/run-e2e.js:2:10)
    at module.exports (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/lib/modes/index.js:11:33)
    at /github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/lib/cypress.js:86:34
    at tryCatcher (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/method.js:39:29)
    at Object.runElectron (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/lib/cypress.js:72:23)
    at Object.startInMode (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/lib/cypress.js:249:21)
    at /github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/lib/cypress.js:186:19
    at tryCatcher (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._settlePromise (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:617:21)
    at Promise._settlePromise0 (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._settlePromise (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:617:21)
    at Promise._settlePromise0 (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:673:18)
    at PromiseArray._resolve (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise_array.js:127:19)
    at PromiseArray._promiseFulfilled (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise_array.js:145:14)
    at Promise._settlePromise (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:609:26)
    at Promise._settlePromise0 (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:673:18)
    at /github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/nodeback.js:42:21
    at /github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14
    at FSReqCallback.oncomplete (fs.js:171:23)
os.js:270
    throw new ERR_SYSTEM_ERROR(ctx);
    ^

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_get_passwd returned ENOENT (no such file or directory)
    at Object.userInfo (os.js:270:11)
    at new File (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/lib/util/file.js:26:62)
    at Object.<anonymous> (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/lib/cache.js:8:18)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/lib/user.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/lib/exception.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at exports.Logger.logger.createException (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/lib/logger.js:60:10)
    at exports.Logger.logger.defaultErrorHandler (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/lib/logger.js:92:10)
    at exports.Logger.exitOnError (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/lib/logger.js:54:19)
    at exports.Logger.Logger._uncaughtException (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/winston/lib/winston/logger.js:645:12)
    at process.emit (events.js:327:22)
    at processEmit [as emit] (/github/home/.cache/Cypress/8.0.0/Cypress/resources/app/packages/server/node_modules/signal-exit/index.js:161:32)
    at process._fatalException (internal/process/execution.js:156:25) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: -2,
    code: 'ENOENT',
    message: 'no such file or directory',
    syscall: 'uv_os_get_passwd'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}
Test run failed, code 7
More information might be available above
Cypress module has returned the following error message:
Could not find Cypress test run results
Error: Could not find Cypress test run results
```

The specific config for this job includes:
```
with:
  start: yarn start:ws # custom job to run 'local-web-server' and serve a static bundle
  wait-on: 'http://localhost:8080'
  browser: chrome
  headless: true
  spec: cypress/integration/accessibility_tests.spec.js
```

**Comment by MikeMcC399** [comment]
Hi @dzervoudakes 

It seems that this issue is now out of date.

The file you referred to https://github.com/cypress-io/cypress/blob/develop/cli/NPM_README.md and the webpage https://www.npmjs.com/package/cypress now show:

![image](https://user-images.githubusercontent.com/66998419/207881226-92e3c2da-17a4-46cc-9875-b6a6828a2fa0.png)

which links to https://docs.cypress.io/guides/getting-started/installing-cypress and scrolling down that page the Section [Node.js](https://docs.cypress.io/guides/getting-started/installing-cypress#Node-js) shows the following:

![image](https://user-images.githubusercontent.com/66998419/207881537-632939b4-3d4b-4d54-99eb-53d0d8f49bbb.png)

The current version for `cypress-io/github-action@v2` is now v5.

**Comment by dzervoudakes** [comment]
Thank you for finally getting back to me.  I can also confirm we upgraded to newer versions and have not run into any issues since.  Closing this issue.
