### ISSUE TITLE
browserslist in angular app is leading to webpack error after updating to chrome >= 116

### ISSUE THREAD

**Issue by chuma2150** [cypress-io/cypress-documentation#5530]
### Description

with Cypress 13.3.0 (any >= 13.0.0) with and Angular app and a browserlist (Chrome >= 116) the cypress run throws: Error: For the selected environment is no default script chunk format available:...

### URL of Issue(s)

n.A.

### Steps to replicate

Create Angular APP
Add .browserslistrc
Add values: Chrome >= 116
Use cypress 13.3.0

### Browser

Chrome >= 116

### Device

- [X] PC
- [X] Mac
- [ ] iPhone
- [ ] iPad
- [ ] Android Phone
- [ ] Android Tablet

### Additional Information

Full error:

Works with Chrome >= 115. But fails on >= 116

Error: For the selected environment is no default script chunk format available:
JSONP Array push can be chosen when 'document' or 'importScripts' is available.
CommonJs exports can be chosen when 'require' or node builtins are available.
Make sure that your 'browserslist' includes only platforms that support these features or select an appropriate 'target' to allow selecting a chunk format by default. Alternatively specify the 'output.chunkFormat' directly.
    at C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\webpack\lib\config\defaults.js:915:11
    at F (C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\webpack\lib\config\defaults.js:94:15)
    at applyOutputDefaults (C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\webpack\lib\config\defaults.js:896:2)
    at applyWebpackOptionsDefaults (C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\webpack\lib\config\defaults.js:229:2)
    at createCompiler (C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\webpack\lib\webpack.js:80:2)
    at create (C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\webpack\lib\webpack.js:143:16)
    at webpack (C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\webpack\lib\webpack.js:167:32)
    at f (C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\webpack\lib\index.js:72:16)
    at C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-preprocessor\dist\index.js:180:46
    at Object.handler (C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\@packages\server\node_modules\@cypress\webpack-batteries-included-preprocessor\index.js:213:40)
    at invoke (C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_plugins.js:183:18)
    at C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\util.js:59:14
    at tryCatcher (C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\bluebird\js\release\util.js:16:23)
    at Function.Promise.attempt.Promise.try (C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\bluebird\js\release\method.js:39:29)
    at Object.wrapChildPromise (C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\util.js:58:23)
    at Object.wrap (C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\preprocessor.js:47:8)
    at RunPlugins.execute (C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_plugins.js:157:29)
    at EventEmitter.<anonymous> (C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\child\run_plugins.js:56:12)
    at EventEmitter.emit (node:events:513:28)
    at EventEmitter.emit (node:domain:489:12)
    at process.<anonymous> (C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\@packages\server\lib\plugins\util.js:33:22)
    at process.emit (node:events:513:28)
    at process.emit (node:domain:489:12)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (C:\Users\mau\AppData\Local\Cypress\Cache\13.3.0\Cypress\resources\app\node_modules\@cspotcode\source-map-support\source-map-support.js:745:40)
    at emit (node:internal/child_process:937:14)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by MikeMcC399** [comment]
@chuma2150 

This is a strange bug and I was able to reproduce it

Angular: 16.2.5
Node.js:    18.18.0
browserslist:   4.22.1
typescript: 4.9.5

@angular-devkit 16.2.5
uses webpack@5.88.2 - same as Cypress

As a workaround you could use
`.browserslist`
```text
last 2 versions
```

`npx browserslist` then shows

```text
and_chr 117
and_ff 117
and_qq 13.1
and_uc 15.5
android 117
baidu 13.18
bb 10
bb 7
chrome 117
chrome 116
edge 117
edge 116
firefox 117
firefox 116
ie 11
ie 10
ie_mob 11
ie_mob 10
ios_saf 17.0
ios_saf 16.6
kaios 3.0-3.1
kaios 2.5
op_mini all
op_mob 73
opera 102
opera 101
safari 17.0
safari 16.6
samsung 22
samsung 21
```

It's possibly a `webpack` (or `browserslist`) bug. I'm unsure if there is anything that Cypress can do to fix it.

This posting is actually in the wrong place, as this issue list is for errors in the documentation on https://docs.cypress.io/, not for suspected bugs in the Cypress software itself.

**Comment by chuma2150** [comment]
@MikeMcC399  thanks for the reply.
Indeed, the workaround works. Resp. I did now extract it to be its own project. 

Sorry for misplacement. Was unsure if it cypress wich should somewhat still work but looks like webpack preprocessor/webpack gets mixed up.

Will close it then.

**Comment by MikeMcC399** [comment]
@chuma2150 

Cypress makes a lot of use of `webpack.config` files, so it could be a problem there. I will submit this issue to the Cypress issue list as I can easily reproduce it using one of the Cypress example repos.

The Cypress engineering team can then decide if it something which can be fixed by them or whether it is a bug in `webpack` for instance.

**Comment by MikeMcC399** [comment]
It is also reproducible without using Angular, only using webpack and Cypress.

**Comment by MikeMcC399** [comment]
- Issue is now logged in https://github.com/cypress-io/cypress/issues/28029
