### ISSUE TITLE
Broken link in "Migrating from Selenium to Cypress"

### ISSUE THREAD

**Issue by MikeMcC399** [cypress-io/cypress-documentation#5794]
### Subject

[Migrating from Selenium to Cypress](http://localhost:3000/guides/end-to-end-testing/selenium-to-cypress)

## Issue

The new page [Migrating from Selenium to Cypress](http://localhost:3000/guides/end-to-end-testing/selenium-to-cypress) from merged PR https://github.com/cypress-io/cypress-documentation/pull/5780 has not been successfully published.

CircleCI shows a [build failure](https://app.circleci.com/pipelines/github/cypress-io/cypress-documentation/24966/workflows/5d668ca8-f84c-4e9b-b44e-6f71d65240ad/jobs/62734/parallel-runs/0/steps/0-105)

```text
 Error: Unable to build website for locale en.
    at tryToBuildLocale (/home/circleci/repo/node_modules/@docusaurus/core/lib/commands/build.js:55:19)
    at async mapAsyncSequential (/home/circleci/repo/node_modules/@docusaurus/utils/lib/jsUtils.js:44:24)
    at async Command.build (/home/circleci/repo/node_modules/@docusaurus/core/lib/commands/build.js:82:21) {
  [cause]: Error: Docusaurus found broken links!

  Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
  Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

  Exhaustive list of all broken links found:
  - Broken link on source page path = /guides/end-to-end-testing/selenium-to-cypress:
     -> linking to /guides/cloud/analytics
```

## Suggestion

Change `/guides/cloud/analytics` to `/guides/cloud/analytics/overview`

**Comment by MikeMcC399** [comment]
- See PR https://github.com/cypress-io/cypress-documentation/pull/5795 for resolution
