### ISSUE TITLE
add cypress-testrail-reporter to docs 

### ISSUE THREAD

**Issue by ValerieThoma** [cypress-io/cypress-documentation#591]
[`cypress-testrail-reporter`](https://github.com/Vivify-Ideas/cypress-testrail-reporter)
Where to add?  Maybe plugins, not sure. _tbd_

**Comment by jennifer-shehane** [comment]
It should definitely be in the 'plugins' page - the main prob is that the "Plugins" doesn't really define only "plugins" anymore - it has custom commands and integrations that don't use the plugins interface. It's probably fine for now, but maybe the description at the top needs some work to include a broader definition of what the list entails.

**Comment by RMoroney** [comment]
@ValerieThoma Hey i am trying to do integration of cypress with testrail but getting following error.

Can you please let me know the steps to do this integration?
```
 Error: getaddrinfo ENOTFOUND https https:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'https',
  host: 'https',
  port: 443,
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
        'User-Agent': 'axios/0.18.0',
        'Content-Length': 180 },
     method: 'post',
     url: 'https://https://agspace.testrail.com/index.php?/api/v2/add_run/9',
     auth:
      { username: 'reema.raole@ag-space.com',
        password: '1vGLLdEhattgsPjvioEM0BC1' },
     data: '{"suite_id":184,"name":"Automated test run Apr 25th 2019, 15:11 (+01:00)","description":"For the Cypress run visit https://dashboard.cypress.io/#/projects/runs","include_all":true}' },
  request:
   Writable {
     _writableState:
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     domain: null,
     _events:
      { response: [Function: handleResponse],
        error: [Function: handleRequestError] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _options:
      { maxRedirects: 21,
        maxBodyLength: 10485760,
        protocol: 'https:',
        path: '//agspace.testrail.com/index.php?/api/v2/add_run/9',
        method: 'post',
        headers: [Object],
        agent: undefined,
        auth: 'reema.raole@ag-space.com:1vGLLdEhattgsPjvioEM0BC1',
        hostname: 'https',
        port: null,
        nativeProtocols: [Object],
        pathname: '//agspace.testrail.com/index.php',
        search: '?/api/v2/add_run/9' },
     _ended: false,
     _ending: true,
     _redirectCount: 0,
     _redirects: [],
     _requestBodyLength: 180,
     _requestBodyBuffers: [ [Object] ],
     _onNativeResponse: [Function],
     _currentRequest:
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: false,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'POST //agspace.testrail.com/index.php?/api/v2/add_run/9 HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json\r\nUser-Agent: axios/0.18.0\r\nContent-Length: 180\r\nHost: https\r\nAuthorization: Basic cmVlbWEucmFvbGVAYWctc3BhY2UuY29tOjF2R0xMZEVoYXR0Z3NQanZpb0VNMEJDMQ==\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '//agspace.testrail.com/index.php?/api/v2/add_run/9',
        _ended: false,
        res: null,
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Circular],
        [Symbol(outHeadersKey)]: [Object] },
     _currentUrl: 'https://reema.raole%40ag-space.com:1vGLLdEhattgsPjvioEM0BC1@https//agspace.testrail.com/index.php?/api/v2/add_run/9' },
  response: undefined }
```

**Comment by estefafdez** [comment]
I'm having this error too. Is there any way to solve it? thanks

**Comment by jennifer-shehane** [comment]
@RMoroney @estefafdez Please open an issue in https://github.com/Vivify-Ideas/cypress-testrail-reporter. This plugin is not under cypress's control.
