### ISSUE TITLE
I know another language, and would love to contribute!

### ISSUE THREAD

**Issue by wataruoguchi** [cypress-io/cypress-documentation#602]
Hi cypress team!

Thank you for building this project! I lately started using cypress, and I love it. porting from selenium is easy, APIs are well designed, and most importantly, it's fast 🚀
I'd like to translate the docs in Japanese if it's helpful for the community. I'm wondering where to create translated md files, and how you integrate that.
As I see md files under `source/`, it'd be under `source/ja/` or something?

Let me know if you have any particular guideline for translation, or if not I'm happy to collaborate.

**Comment by jennifer-shehane** [comment]
Yay! 🙌 

Yes, there would need to be some slight updates and tests done on our part, as I just put off doing the work until there was another language. But, I will update this as soon as there are translated files submitted. 

- First, create a PR off of `develop` for any of the work you do. 

- There should be an equivalent `ja.yml` file used here for general link names and navigation: https://github.com/cypress-io/cypress-documentation/tree/develop/themes/cypress/languages

- Yes, there would be a `ja` folder created under `source` that would then reflect the general structure that exists in `source`. So, it would have it's own folders and files like this inside of it:

<img width="311" alt="screen shot 2018-05-18 at 9 53 41 am" src="https://user-images.githubusercontent.com/1271364/40238524-6aee9af0-5a81-11e8-9bbb-83a7ee8a1125.png">

Our internationalization structure is based off of how `hexo` generated their own documentation, if that repo helps at all: https://github.com/hexojs/site/tree/master/source

Let me know if you have any more questions.

**Comment by wataruoguchi** [comment]
@jennifer-shehane Thanks for the advice.
How are you building this?
After running `npm i && npm run build` I am seeing a lot of 400/500 errors

```
disabling filter cleanup for environment development                                               
in environment development site url is https://docs.cypress.io                               
NODE_ENV is: development                                            
INFO  Start processing                                                                      
StatusCodeError: 500 - ""                                            
    at new StatusCodeError (/<somewhere>/cypress-documentation/node_modules/request-promise-core/lib/errors.js:32:15)
    at /<somewhere>/cypress-documentation/node_modules/request-promise-core/lib/plumbing.js:97:41
    at runCallback (timers.js:773:18)             
    at tryOnImmediate (timers.js:734:5)    
    at processImmediate [as _immediateCallback] (timers.js:711:5)
From previous event:                    
    at Request.plumbing.init (/<somewhere>/cypress-documentation/node_modules/request-promise-core/lib/plumbing.js:36:28)
    at Request.RP$initInterceptor [as init] (/<somewhere>/cypress-documentation/node_modules/request-promise-core/configure/request2.js:41:27)
    at new Request (/<somewhere>/cypress-documentation/node_modules/request/request.js:128:8)
    at request (/<somewhere>/cypress-documentation/node_modules/request/index.js:53:10)
    at validateExternalUrl (/<somewhere>/cypress-documentation/lib/url_generator.js:118:10)
    at keyv.set.then (/<somewhere>/cypress-documentation/lib/url_generator.js:294:16)
    at <anonymous>                                     
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by wataruoguchi** [comment]
My machine is not a great environment for building this Hexo project. Super slow. I hope somebody else to continue this translation.

**Comment by jennifer-shehane** [comment]
Yeah, it is a bit clunky at the moment. 

Some notes on things I need to do:
- Add tests for language selection
- Link to 'edit' doc should go to corresponding language dir
- Document/build process around updating English docs -> updating translated equivalent.
- Have sidebar/all links go to corresponding language dir

**Comment by brian-mann** [comment]
`npm start -- --no-validate` will skip all of those initial URL checks. The docs are in bad need of an upgrade to rework a lot of internal stuff.

**Comment by jennifer-shehane** [comment]
Closing due to inactivity.
